/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author korisnik
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
         setTitle("Glavna forma");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        frmPrikljucak = new javax.swing.JMenuItem();
        frmMolbaZaUrbanizam = new javax.swing.JMenuItem();
        frmObjekat = new javax.swing.JMenuItem();
        frmZaposleni = new javax.swing.JMenuItem();
        frmGrad = new javax.swing.JMenuItem();
        frmZahtev = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Izaberi formu");

        frmPrikljucak.setText("Priključak");
        frmPrikljucak.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                frmPrikljucakMouseClicked(evt);
            }
        });
        frmPrikljucak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frmPrikljucakActionPerformed(evt);
            }
        });
        jMenu1.add(frmPrikljucak);

        frmMolbaZaUrbanizam.setText("Molba za Urbanizam");
        jMenu1.add(frmMolbaZaUrbanizam);

        frmObjekat.setText("Objekat");
        jMenu1.add(frmObjekat);

        frmZaposleni.setText("Zaposleni");
        frmZaposleni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frmZaposleniActionPerformed(evt);
            }
        });
        jMenu1.add(frmZaposleni);

        frmGrad.setText("Grad");
        frmGrad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frmGradActionPerformed(evt);
            }
        });
        jMenu1.add(frmGrad);

        frmZahtev.setText("Zahtev");
        frmZahtev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frmZahtevActionPerformed(evt);
            }
        });
        jMenu1.add(frmZahtev);

        jMenuBar1.add(jMenu1);
        jMenu1.getAccessibleContext().setAccessibleName("File");

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void frmPrikljucakMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_frmPrikljucakMouseClicked

    }//GEN-LAST:event_frmPrikljucakMouseClicked

    private void frmZaposleniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frmZaposleniActionPerformed
        try {
            ZaposleniForm frmZaposleni = new ZaposleniForm();
            frmZaposleni.setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Došlo je do greške: " + ex.getMessage(), "Greška", JOptionPane.ERROR_MESSAGE);
        } 
    }//GEN-LAST:event_frmZaposleniActionPerformed

    private void frmGradActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frmGradActionPerformed

try {
            GradForm frmGrad = new GradForm();
            frmGrad.setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Došlo je do greške: " + ex.getMessage(), "Greška", JOptionPane.ERROR_MESSAGE);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_frmGradActionPerformed

    private void frmPrikljucakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frmPrikljucakActionPerformed
         try {
            PrikljucakForm frmPrikljucak = new PrikljucakForm();
            frmPrikljucak.setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Došlo je do greške: " + ex.getMessage(), "Greška", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_frmPrikljucakActionPerformed

    private void frmZahtevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frmZahtevActionPerformed
         try {
            ZahtevForm frmZahtev = new ZahtevForm();
            frmZahtev.setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Došlo je do greške: " + ex.getMessage(), "Greška", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_frmZahtevActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem frmGrad;
    private javax.swing.JMenuItem frmMolbaZaUrbanizam;
    private javax.swing.JMenuItem frmObjekat;
    private javax.swing.JMenuItem frmPrikljucak;
    private javax.swing.JMenuItem frmZahtev;
    private javax.swing.JMenuItem frmZaposleni;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
