CREATE USER C##APP_USER IDENTIFIED BY Root1234;
GRANT CONNECT, RESOURCE TO C##APP_USER;

GRANT CREATE TABLE TO C##APP_USER;
GRANT CREATE VIEW TO C##APP_USER;
GRANT CREATE SEQUENCE TO C##APP_USER;
GRANT CREATE TRIGGER TO C##APP_USER;
GRANT CREATE PROCEDURE TO C##APP_USER;
GRANT CREATE TYPE TO C##APP_USER;
GRANT CREATE SYNONYM TO C##APP_USER;

